const idiomas = {
  pt_BR: {
    nomeSistema: "Sistema Pax Primavera",
    inputCpf: "CPF",
    inputSenha: "Senha",
    esqueceu_senha: "Problemas com seu acesso?",
    idioma: "Selecione o idioma:",
    br: "Português(BR)",
    py: "Espanhol(PY)",
    bt_logar: "ENTRAR",
    versao: "Versão",
    toastLogin: "Bem vindo(a)",
    toastSenha: "Senha incorreta!",
    toastUsuario: "Usuário não encontrado!",
    toastErro: "Preencha todos os campos!",
    cadastro: "Primeira vez aqui?",
    cadastroNome: "Nome Completo",
    cadastroEmail: "E-mail",
    cadastroSetor: "Setor",
  },
  es_PY: {
    nomeSistema: "Sistema Pax Primavera",
    inputCpf: "Usuario",
    inputSenha: "Contraseña",
    esqueceu_senha: "¿Problemas con tu acceso?",
    idioma: "Selecciona el idioma:",
    br: "Portugués(BR)",
    py: "Español(PY)",
    bt_logar: "INICIAR SESIÓN",
    versao: "Versión",
    toastLogin: "Bem vindo(a)",
    toastSenha: "Contraseña incorrecta!",
    toastUsuario: "Usuario no encontrado!",
    toastErro: "Complete todos los campos!",
    cadastro: "¿Primera vez aquí?",
    cadastroNome: "Nombre completo",
    cadastroEmail: "Correo Electrónico",
    cadastroSetor: "Sector",
  },
};

export default idiomas;
